name: sofiakb_router
description: The packages allows to manage routes.
maintainer: Sofiane Akbly
version: 1.0.0-beta.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
